/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import codes.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Shan
 */
public class product extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    
    public product() {
        initComponents();
        conn=DBconnect.connect();
    }
    
    public void tabledata(){
        int r = ptable.getSelectedRow();
        
        String id = ptable.getValueAt(r, 0).toString();
        String type = ptable.getValueAt(r, 1).toString();
        String price = ptable.getValueAt(r, 2).toString();
        
        idbox.setText(id);
        pnamebox.setText(type);
        pricebox.setText(price);
    }
    
    public void clean(){
        inbox.setSelectedIndex(0);
        idbox.setText("");
        pnamebox.setText("");
        pricebox.setText("");
    }
    
    
    public void tableloadp(){
        String ins;
        ins = inbox.getSelectedItem().toString();
        
        if(ins.equals("Gitar")){
           try {
                String sql = "SELECT gid AS ID,gtype AS Type,gprice AS Price FROM guitar" ;
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
            
                ptable.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
            }
        }
        else if(ins.equals("Drum")){
            try {
                String sql = "SELECT did AS ID,dtype AS Type,dprice AS Price FROM drum" ;
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
            
                ptable.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
            }
            
        }
        else if(ins.equals("Keybord")){
            try {
                String sql = "SELECT kid AS ID,ktype AS Type,kprice AS Price FROM keyboard" ;
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
            
                ptable.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
            }
            
        }
        else if(ins.equals("Octerpad")){
            try {
                String sql = "SELECT oid AS ID,otype AS Type,oprice AS Price FROM octapad" ;
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
            
                ptable.setModel(DbUtils.resultSetToTableModel(rs));
            
            } catch (Exception e) {
            }
            
        }
    
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idbox = new javax.swing.JTextField();
        pnamebox = new javax.swing.JTextField();
        pricebox = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        peditbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        inbox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ptable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Panel");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shan\\Downloads\\Product-documentation-icon.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shan\\Downloads\\Back-2-2-icon2.png")); // NOI18N
        jLabel7.setToolTipText("Back");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7)
                .addGap(228, 228, 228)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 110));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 900, 10));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Product Name");

        jLabel3.setText("Product ID");

        jLabel4.setText("Product Price");

        idbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idboxActionPerformed(evt);
            }
        });

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        peditbtn.setText("Edit");
        peditbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peditbtnActionPerformed(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Instument");

        inbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Drum", "Keybord", "Gitar", "Octerpad", "Floot", "Others" }));
        inbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inboxActionPerformed(evt);
            }
        });

        jButton1.setText("Clean");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addbtn)
                        .addGap(18, 18, 18)
                        .addComponent(peditbtn)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idbox)
                            .addComponent(pnamebox)
                            .addComponent(pricebox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(deletebtn)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pricebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn)
                    .addComponent(peditbtn)
                    .addComponent(deletebtn)
                    .addComponent(jButton1))
                .addGap(65, 65, 65))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 340, 360));

        ptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ptable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 540, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        String id;
        String pname;
        String price;
        
        id = idbox.getText();
        pname = pnamebox.getText();
        price = pricebox.getText();
        
        String ins;
        ins = inbox.getSelectedItem().toString();
        
        if(ins.equals("Gitar")){
            try {
                String sql = "INSERT INTO guitar (gid,gtype,gprice)VALUES('"+id+"','"+pname+"','"+price+"')";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Inserted...");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(ins.equals("Drum")){
            try {
                String sql = "INSERT INTO  drum (did,dtype,dprice)VALUES('"+id+"','"+pname+"','"+price+"')";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Inserted...");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(ins.equals("Keybord")){
            try {
                String sql = "INSERT INTO keyboard (kid,ktype,kprice)VALUES('"+id+"','"+pname+"','"+price+"')";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Inserted...");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
        }
        else if(ins.equals("Octerpad")){
            try {
                String sql = "INSERT INTO octapad (oid,otype,oprice)VALUES('"+id+"','"+pname+"','"+price+"')";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Inserted...");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } 
        }
        tableloadp();
    }//GEN-LAST:event_addbtnActionPerformed

    private void idboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idboxActionPerformed

    private void inboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboxActionPerformed
        tableloadp();
        
    }//GEN-LAST:event_inboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clean();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        int check = JOptionPane.showConfirmDialog(null, "Do you Want to DELETE this Product...");
        
        if(check == 0){
            String id = idbox.getText();
            
        String ins;
        ins = inbox.getSelectedItem().toString();
            
            if(ins.equals("Gitar")){
               try {
                String sql = "DELETE FROM guitar WHERE gid='"+id+"'";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted...");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error..!");
            }
        }
        else if(ins.equals("Drum")){
            try {
                String sql = "DELETE FROM drum WHERE did='"+id+"'";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted...");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error..!");
            }
        }
        else if(ins.equals("Keybord")){
            try {
                String sql = "DELETE FROM keyboard WHERE kid='"+id+"'";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted...");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error..!");
            } 
        }
        else if(ins.equals("Octerpad")){
            try {
                String sql = "DELETE FROM octapad WHERE oid='"+id+"'";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted...");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error..!");
            } 
        }
        
        }
       tableloadp();
       clean();
    }//GEN-LAST:event_deletebtnActionPerformed

    private void ptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptableMouseClicked
        tabledata();
    }//GEN-LAST:event_ptableMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        amainf m22 = new amainf();
        m22.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void peditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peditbtnActionPerformed
        String ins;
        String id = idbox.getText();
        String name1 = pnamebox.getText();
        String price = pricebox.getText();
        
        ins = inbox.getSelectedItem().toString();
        
        if(ins.equals("Gitar")){
               try {
                String sql = "UPDATE guitar SET gtype ='"+name1+"',gprice ='"+price+"' WHERE gid ='"+id+"'";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Updated ...!");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(ins.equals("Drum")){
            try {
                String sql = "UPDATE drum SET dtype ='"+name1+"',dprice ='"+price+"' WHERE did ='"+id+"'";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Updated ...!");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error..!");
            }
        }
        else if(ins.equals("Keybord")){
            try {
                String sql = "UPDATE keyboard SET ktype ='"+name1+"',kprice ='"+price+"' WHERE kid ='"+id+"'";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Updated ...!");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error..!");
            } 
        }
        else if(ins.equals("Octerpad")){
            try {
                String sql = "UPDATE octapad SET otype ='"+name1+"',oprice ='"+price+"' WHERE oid ='"+id+"'";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Updated ...!");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error..!");
            } 
        }
        tableloadp();
        
    }//GEN-LAST:event_peditbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField idbox;
    private javax.swing.JComboBox<String> inbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton peditbtn;
    private javax.swing.JTextField pnamebox;
    private javax.swing.JTextField pricebox;
    private javax.swing.JTable ptable;
    // End of variables declaration//GEN-END:variables
}
